name: Vulnerability scan
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        DISTRIB_ID: [ubuntu]
        DISTRIB_RELEASE: [latest, 20.04, 18.04, 16.04]
        IMAGE_TYPE: [act, runner]
    steps:
      - uses: azure/container-scan@v0
        with:
          image-name: ghcr.io/catthehacker/${{ matrix.DISTRIB_ID }}:${{ matrix.IMAGE_TYPE }}-${{ matrix.DISTRIB_RELEASE }}
